Add field needed for MySQL 5.7 compatibility with SELECT DISTNCT .. ORDER BY
SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is
not in SELECT list, references column 'zoph.pp.position' which is not in
SELECT list; this is incompatible with DISTINCT
Fatal Error: SQL failed db.inc.php: 156.

Issue #88